### ISSUE TITLE
关于Deformable Alignment的一些疑问

### ISSUE THREAD

**Issue by BinLi-git** [Algolzw/EBSR#10]
作者您好，首先我看到您的这个工作我非常的兴奋和激动，我对Deformable Alignment很感兴趣但是却又对此感到困惑，下面请允许我用中文提问关于Deformable Alignment的一些疑问。我想知道关于Deformable Alignment这个模块有单独的loss来约束吗？这个模块有gt来监督吗？可以将对齐的结果可视化吗？以此达到令人信服的结果。期待作者的回答，谢谢。

**Comment by Algolzw** [comment]
我们只对SR结果使用L1来约束，没有额外的Loss。当然也可以用(参考DTAN)，不过我们的实验看来不过效果提升不大。可视化特征上的对齐结果你可以参考EDVR。

**Comment by BinLi-git** [comment]
好的，非常感谢
