### ISSUE TITLE
Training time?

### ISSUE THREAD

**Issue by ruoshiliu** [Algolzw/EBSR#3]
Hi,

Great work! Your paper mentions you implemented the model on 4 RTX 2080 Ti GPU. For the model that generate the results in the NTIRE challenge, how many epochs did you train and how long did it take (for pretraining and finetuning individually)?

Thanks,
Ruoshi

**Comment by Algolzw** [comment]
Our model was trained with 400 epochs. 
One week for pretraining and one day for finetuning.
