### ISSUE TITLE
PSNR result in paper

### ISSUE THREAD

**Issue by yjsunnn** [Algolzw/EBSR#5]
Hi @Algolzw Thanks a lot for your wonderful work in EBSR. I have some questions about the EDVR result in your paper. In Section4 Table1, EDVR on Track2 achieves 46.168 on PSNR metric and you mentioned this model is training from scratch. I use the original EDVR code (https://github.com/xinntao/BasicSR/blob/master/basicsr/models/edvr_model.py) and train the model from scratch on real-world BurstSR dataset. But the psnr is around ~27dB. So could you please give me some suggestions? Any suggestion would help me a lot.

**Comment by Algolzw** [comment]
Our code is used for training synthetic data, if you want to train it (or EDVR) on Track2, you may need to use AlignedL1 loss in https://github.com/Algolzw/EBSR/blob/main/utils/metrics.py.

**Comment by yjsunnn** [comment]
Thanks a lot for your help. I will definitely try it. THANK YOU :)
