### ISSUE TITLE
train dataset

### ISSUE THREAD

**Issue by zhengqianisme** [Algolzw/EBSR#7]
Hi @Algolzw Thanks a lot for your wonderful work in EBSR. I have some questions about the train dataset.What is the data set used for the pre_training model？is BurstSR synthetic dataset or Zurich RAW to RGB Dataset？thanks a lot！

**Comment by Algolzw** [comment]
We pre-train the model with synthetic data based on ZurichRAWtoRGB Dataset. The processing code can be find in the [DBSR rep](https://github.com/goutamgmb/deep-burst-sr/blob/master/data/synthetic_burst_generation.py).

**Comment by zhengqianisme** [comment]
Thanks for your reply！In addition，Are the input and output of the network(ebsr model) raw images?Then,use "SimplePostProcess()"to to turn output raw image into rgb image?

**Comment by Algolzw** [comment]
The output of EBSR is 16-bit RGB images. We use "SimplePostProcess" and "BurstSRPostProcess" for synthetic data and real data, respectively, to visualize images with original meta-info. For more details please refer [test_real.py](https://github.com/Algolzw/EBSR/blob/main/test_real.py)
