### ISSUE TITLE
Checkpoint for Track 2

### ISSUE THREAD

**Issue by Magauiya** [Algolzw/EBSR#8]
Dear authors,

Thank you for publishing the code including pretrained model. Can you share the model weights for the Track 2 (Real Burst SR case)? 
It would give a great opportunity to the research community to compare their methods with your SOTA solution.

Sincerely,
Magauiya

**Comment by Algolzw** [comment]
Well, we are pleased to release the model weights for Track 2 next week.

Best,
Luo

**Comment by Algolzw** [comment]
Hi, we have uploaded a pre-trained model for real track [here](https://drive.google.com/file/d/1Zz21YwNtiKZCjerrZsdvcWyubqTJBwaD/view?usp=sharing). And we also updated our code to support real data testing.
